[package]
name = "vxi11"
version = "0.1.0"
authors = ["John Stanford <johnwstanford@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.4"
lazy_static = "1.4.0"
rand = "0.3"
regex = "1.3.5"
rustfft = "3.0.0"
